---
# Configuration file for Mega-Linter
# See all available variables at https://nvuillam.github.io/mega-linter/configuration/ and in linters documentation

PRINT_ALPACA: false
# APPLY_FIXES: all # all, none, or list of linter keys
DEFAULT_BRANCH: main # Usually master or main
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
# DISABLE:
#  - COPYPASTE # Comment to disable checks of abusive copy-pastes
#  - SPELL # Comment to disable checks of spelling mistakes # - SPELL # Uncomment to disable checks of spelling mistakes
SHOW_ELAPSED_TIME: false
FILEIO_REPORTER: false
ADDITIONAL_EXCLUDED_DIRECTORIES:
  - plugged
  - _site
  - report
DISABLE_LINTERS:
  - JAVASCRIPT_STANDARD
LINTER_RULES_PATH: https://raw.githubusercontent.com/joe-sharp/linter-configs/main
RUBY_RUBOCOP_CONFIG_FILE: .rubocop.yml
YAML_YAMLLINT_CONFIG_FILE: .yamllint.yml

BASH_SHFMT_ARGUMENTS: -i 2 -kp -sr
SPELL_CSPELL_ARGUMENTS: --no-must-find-files
CREDENTIALS_FILTER_REGEX_EXCLUDE: report
PRE_COMMANDS:
  - command: sed -i "s/- 'tmp\/\*\*\/\*'//g" $(rubocop -d --force-default-config -v | grep Default | awk '{print $4}')
    cwd: "root"
