---

Layout/LineLength:
  Enabled: true
  Max: 120

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 10
# Pending
# Style/HashEachMethods:
#  Enabled: true

# Style/HashTransformKeys:
#  Enabled: true

# Style/HashTransformValues:
#  Enabled: true
